### ISSUE TITLE
unresolved import `fast_qr::convert::image` could not find `image` in `convert`

### ISSUE THREAD

**Issue by korykim** [erwanvivien/fast_qr#10]
### problem
- unresolved import `fast_qr::convert::image` could not find `image` in `convert`

### dependencies
```
[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
fast_qr="0.6.1"
```

**Comment by erwanvivien** [comment]
Hello @korykim 

The `convert::image` module is behind a feature since it adds a dependency.

Your Cargo.toml could look like this:

```toml
fast_qr = { version = "0.6.1", features = ["image"] }
```

Tell me if that resolves the issue! 👍

**Comment by korykim** [comment]
> 你好@korykim
> 
> 该模块位于功能后面，因为它添加了依赖项。`convert::image`
> 
> 您的 Cargo.toml 可能如下所示：
> 
> ```toml
> fast_qr = { version = "0.6.1", features = ["image"] }
> ```
> 
> 告诉我这是否可以解决问题！👍

Problem solved.
Thanks, Bro!
