### ISSUE TITLE
Remove `Cargo.lock`

### ISSUE THREAD

**Issue by AntoniosBarotsis** [erwanvivien/fast_qr#14]
According to the [Cargo book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock)

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put `Cargo.lock` in your `.gitignore`.

I came across an issue while upgrading to `0.8.0` because I also required `png = "0.17.7"` while `fast_qr` lists `png = "0.17.6"`.

In my case it doesn't matter but this could cause future annoyance (or actual issues) to someone else. Perhaps we should remove `main.rs` and put the contained code into an `examples` directory (which you can run easily with cargo).

I could make a pr for this if you agree sometime soon-ish :)

**Comment by erwanvivien** [comment]
A PR would be welcome, maybe we could even split the examples in 2/3 mains so we could have the terminal / raw matrix output, the SVG and the image one.

That would imply to bump to 8.1 right ?
