### ISSUE TITLE
Image branding

### ISSUE THREAD

**Issue by sergiomeneses** [erwanvivien/fast_qr#16]
Hey, just wanna know if there is wayt to brand the QR code generated, like colors and logo.

**Comment by erwanvivien** [comment]
Hello, available examples showing how to brand QRCode using colors is availables in [example folder](https://github.com/erwanvivien/fast_qr/blob/master/examples)

There are two ways to add an image to the QRCode:
- One would be to modify the svg string, add <rect /> and <img />. Then do render
- The other one would be to use [to_pixmap](https://github.com/erwanvivien/fast_qr/blob/master/src/convert/image.rs#L102) and edit the image afterward.

I agree this is cumbersome and will be doing an update to add those features.

**Comment by AntoniosBarotsis** [comment]
I manually added a logo on top [here](https://github.com/AntoniosBarotsis/qr-rs/blob/e52799d65f40c2c19ec7405687a69fb219854bd9/lib/src/lib.rs#L206-L241) using the [image](https://github.com/image-rs/image) crate in case that's useful! @sergiomeneses

**Comment by erwanvivien** [comment]
It is non-trivial to solve as from an SVG perspective an image is only a path, an URL (not handled) or a base64 image. It has no information on width, or height. The simplest API I'm thinking of right now requires you to pass the image width and height. Not convenient, but OK

Would that work for now ?

**Comment by erwanvivien** [comment]
I managed to get those results, without need to specify width and height for now.

![out](https://user-images.githubusercontent.com/44021072/214967494-76be8213-8b89-4ff7-9475-ff4dd222ffe3.png)

**Comment by erwanvivien** [comment]
**Square**:
![out](https://user-images.githubusercontent.com/44021072/214970540-ef311f72-5276-4e83-a6c9-f7844133102e.png)

**RoundedSquare**:

![out](https://user-images.githubusercontent.com/44021072/214970712-73d22551-c0b9-4b57-8c91-548483c4635e.png)

![out](https://user-images.githubusercontent.com/44021072/214970860-13de7c78-bb3e-466c-87fd-2490b10bc4ca.png)

**CIRCLE**:
![out](https://user-images.githubusercontent.com/44021072/214970957-ca215275-c4df-4326-89af-c22445e81ed4.png)

![out](https://user-images.githubusercontent.com/44021072/214971013-115f3adc-10d8-4dd8-8a01-ad6ad58b4a0c.png)

This is kinda bad, as we lose lots of modules in the second one

**Comment by erwanvivien** [comment]
Please tell me which one you prefer between 2/3 and 4/5

**Comment by erwanvivien** [comment]
You can play around with the version at [fast_qr/embed-image](https://github.com/erwanvivien/fast_qr/tree/embed-image) with the example as baseline

**Comment by sergiomeneses** [comment]
Hey, i just try the new api, it works nice, i think is better if the user set the percentage of the qr to display image (even ifthe qr it turns to unreadless). Also, i would like to know if there is a way to customize the shapes (both image and modules), i saw these are just svg definitions.

**Comment by erwanvivien** [comment]
I've added in 3c35904a5 the ability to customize the size of the embedded image

**Comment by erwanvivien** [comment]
On the example you provided I see an API where one would provide an Shape::Custom(_) and would be able to provide:

```rust
Shape::Square => format!("M{},{}h1v1h-1", j + self.margin, i + self.margin),
Shape::Circle => format!(
    "M{},{}a.5,.5 0 1,1 0,-.1",
    j + self.margin + 1,
    (i + self.margin) as f64 + 0.5f64
),
Shape::RoundedSquare => format!(
    "M{0}.2,{1}.2 {0}.8,{1}.2 {0}.8,{1}.8 {0}.2,{1}.8z",
    j + self.margin,
    i + self.margin,
),
Shape::Horizontal => {
    format!("M{}.1,{}h1v.8h-1", j + self.margin, i + self.margin)
}
Shape::Vertical => {
    format!("M{},{}.1h.8v1h-.8", j + self.margin, i + self.margin)
}
Shape::Diamond => {
    format!(
        "M{}.5,{}l.5,.5l-.5,.5l-.5,-.5z",
        j + self.margin,
        i + self.margin
    )
}
```

Here can be found the existing shapes, but what would be fed ? `j + margin` could do it, but some (Circle) needs more different, maybe a closure should be passed?

**Comment by erwanvivien** [comment]
Using a close / function would allow previous snippet to be refactored too

**Comment by erwanvivien** [comment]
c8196e4 added possibility to move image

**Comment by erwanvivien** [comment]
On the [fast_qr/embed-image](https://github.com/erwanvivien/fast_qr/tree/embed-image) branch, there is now an example showing how to combine & use custom shape. For now there still only have the same colors tho

<img width="250" src="https://user-images.githubusercontent.com/44021072/215282748-7e081f40-2e83-43b8-b035-9a5a12c30d3f.png"/>

here you see a circle and a rectangle.

**Comment by AntoniosBarotsis** [comment]
Oh so this also works for pngs? Nice!

**Comment by erwanvivien** [comment]
> Oh so this also works for pngs? Nice!

Indeed! I found a bug? in resvg where if the provided image is an svg it's not sized / rendered as it should (expected being Firefox's renderer)

**Comment by erwanvivien** [comment]
I've upgraded the API allowing user to provide different colors for each "layer" and check the type of the module, thus we are now able to have those outputs:

<img src="https://user-images.githubusercontent.com/44021072/215289431-3966194c-6cd6-4af9-bcf4-26eaa1028b06.png" width="250px" />

**Comment by AntoniosBarotsis** [comment]
Make sure to open an issue in the SVG crate! @erwanvivien

**Comment by erwanvivien** [comment]
I will do!

**Comment by erwanvivien** [comment]
After some digging, the inner svg (the one I'm using [above](https://github.com/erwanvivien/fast_qr/blob/master/assets/example.com.svg)) contains a width attribute, which makes it scale down.

To be honest, I don't know which one is right on this, Firefox is clearly ignoring the width attribute and resvg is having a weird behavior(?)

**Comment by sergiomeneses** [comment]
hey @erwanvivien, i will try it this week, thanks.

**Comment by erwanvivien** [comment]
Please do tell me if you need more! Thanks

**Comment by erwanvivien** [comment]
@sergiomeneses Did you manage to try the new API ? :)

**Comment by erwanvivien** [comment]
I will mark the issue as resolved, if you need something more, please file a new issue :)
