### ISSUE TITLE
Support for terminals with light backgrounds

### ISSUE THREAD

**Issue by ForgQi** [erwanvivien/fast_qr#17]
Thank you for your work！
I want to replace `qrcode` with your crate, Is it possible to implement like this for supports both dark and light colored terminals
```rust
    let code = QrCode::new("mow mow").unwrap();
    let image = code.render::<unicode::Dense1x2>()
        .dark_color(unicode::Dense1x2::Light)
        .light_color(unicode::Dense1x2::Dark)
        .build();
    println!("{}", image);
```

**Comment by erwanvivien** [comment]
Hey, there currently is no support for that, I will work on that tomorrow, thanks for the report !

**Comment by erwanvivien** [comment]
To add a bit more information to this issue, currently, the color is indeed set for dark and it is pretty bare-bone: https://github.com/erwanvivien/fast_qr/blob/master/src/helpers.rs#L31-L58

What customisation would you like to see ? Colors ? Module width ? Maybe it working on more terminals than Unix (would require an other crate) ?

**Comment by ForgQi** [comment]
in light backgrounds:

qrcode: 
![image](https://user-images.githubusercontent.com/34411314/216113170-6b6cb2b5-4da2-43c8-a4cb-ba7484f3d950.png)

fast_qr:
![image](https://user-images.githubusercontent.com/34411314/216113886-d460d0f9-6b40-43e3-893b-d5c9d4e254d6.png)

Maybe needs to reverse the color

**Comment by erwanvivien** [comment]
That I understand, do you need anything more ?

**Comment by erwanvivien** [comment]
I removed the custom colors codes I had put, so it works by default, using the terminal default color
