### ISSUE TITLE
After upgrading to 0.8.3, I get index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by svenstaro** [erwanvivien/fast_qr#19]
In my project [miniserve](https://github.com/svenstaro/miniserve/), I get errors from inside `fast_qr` since upgrading to 0.8.3: https://github.com/svenstaro/miniserve/actions/runs/4175872918/jobs/7231388083

I believe this is a bug recently introduced in fast_qr itself.

**Comment by erwanvivien** [comment]
I've looked into it, it is indeed an unfortunate bug from my part...
I would have caught it if I had run the examples (CI or local 🥲)

@AntoniosBarotsis Thanks for the PR, however it does not fix the issue :/
I will fix it in 20-30 min

**Comment by svenstaro** [comment]
Thanks for fixing this. Could you cut a release with this?

**Comment by erwanvivien** [comment]
@svenstaro Sorry I had gone eating :)
The release is now live https://crates.io/crates/fast_qr

**Comment by erwanvivien** [comment]
Thanks for your report, I have now automated those checks and it should not go live again
