### ISSUE TITLE
NodeJS support?

### ISSUE THREAD

**Issue by bitwister** [erwanvivien/fast_qr#25]
Would be nice if this library also worked in NodeJS, since there are no functioning qrcode generation libraries with high performance for NodeJS right now

**Comment by erwanvivien** [comment]
Hello, I have uploaded a Wasm package to npm

```
npm install fast_qr
```

There are examples in the readme! Tell me if you need more, I'm actually using it here https://fast-qr.com

**Comment by erwanvivien** [comment]
Don't mind the UI haha

**Comment by erwanvivien** [comment]
Hmmm, the examples in the readme might be outdated, I'll check that today

**Comment by erwanvivien** [comment]
@bitwister, I've update the readme in 75bc64a

https://github.com/erwanvivien/fast_qr#javascript--typescript

**Comment by erwanvivien** [comment]
Closing this issue as there is no more conversation.
