### ISSUE TITLE
FYI: AGPL licensing

### ISSUE THREAD

**Issue by maxnachlinger** [erwanvivien/fast_qr#26]
This is a nice library, and fast too (I ran my own benchmarks as well) :) Sadly I cannot use it for work due to its [AGPL](https://www.gnu.org/licenses/agpl.html) license. 

You probably know that AGPL requires modified code to be shared with the public and remain under the AGPL license. Also any code linked to the GPL/AGPL code (either dynamically or statically) is considered a combined work and the entire combination must be licensed under GPL/AGPL. So the code I write for work would also have to be open sourced as GPL/AGPL. 

Sadly my employer won't want to share the rest of our codebase that might use this library.

**Comment by erwanvivien** [comment]
Hello 👋 
What license do you think is best suited here? I'll have a look on my side too :)

**Comment by maxnachlinger** [comment]
I like the MIT license since it works for open source and proprietary software and is written in clear language.

**Comment by erwanvivien** [comment]
I'll take a look at this tomorrow then :)

**Comment by maxnachlinger** [comment]
Wow thanks man!

**Comment by erwanvivien** [comment]
No worries
