### ISSUE TITLE
implement error trait for QRCodeError struct

### ISSUE THREAD

**Issue by akhildevelops** [erwanvivien/fast_qr#28]
It would be nice if `std::error::Error` is implemented for `QRCodeError` struct. It will be easy for error handling.

**Comment by erwanvivien** [comment]
Sure, will do :)

**Comment by erwanvivien** [comment]
@akhildevelops Please tell me if this satifies your needs. 
https://github.com/erwanvivien/fast_qr/pull/29

**Comment by akhildevelops** [comment]
Cool @erwanvivien , This is fine but why are you only targeting for non wasm targets.

**Comment by erwanvivien** [comment]
I had not tested, and thought it would increase the Wasm package, but it did not, I updated the PR and will merge it
