### ISSUE TITLE
wasm-bindgen feature

### ISSUE THREAD

**Issue by astrale-sharp** [erwanvivien/fast_qr#37]
For use via wasmi, wasm-bindgen is a problem, would you consider putting it behind a feature? If it's straightforward I could probably even find time to create a PR if you're interested, I have a temporary fix in my fork [here](https://github.com/astrale-sharp/fast_qr)

**Comment by astrale-sharp** [comment]
really nice project btw :3

**Comment by erwanvivien** [comment]
Hey 👋 Could you explain more about why wasm-bindgen is a problem, I'm not aware of the issue!

**Comment by astrale-sharp** [comment]
https://github.com/rustwasm/wasm-bindgen/issues/3421

In my **limited** understanding, wasm-bindgen is made for the web, as such it requires webassembly functions available only through the browser.

But the work here https://github.com/EpicEricEE/typst-plugins is made to bundle fast_qr as a plugin for typst, hence we don't have browser capabilities.

**Comment by astrale-sharp** [comment]
Apparently they're on it so absolutly, i guess !
