### ISSUE TITLE
Make wasm-bindgen optional

### ISSUE THREAD

**Issue by svenstaro** [erwanvivien/fast_qr#4]
This crate, as of the time of writing, only has a single dependency (wasm-bindgen) which is great! But I wonder whether even this dependency could be made optional for those of us who don't need wasm-bindgen.

**Comment by erwanvivien** [comment]
Hello !

Thanks for the heads up, I had this intention ! I will try to make to only dev-dependency or maybe a feature, because it is indeed not needed.

**Comment by erwanvivien** [comment]
@svenstaro I made a 0.5 release where this problem is resolved.

Also, the 0.5 release adds more SVG support on WASM

**Comment by svenstaro** [comment]
Thanks, that's great!
