### ISSUE TITLE
QR Codes are Diagonally Inverted When Rendered as SVGs/PNGs

### ISSUE THREAD

**Issue by Adam-Alj** [erwanvivien/fast_qr#47]
Hey! Big fan of the library, though I came across a strange issue the other day.

Seems as though the QR codes are rendered with a diagonal inversion for image/svg output.

This can be verified by looking at the format information (as per ISO/IEC 18004 2015), specifically the first two error correction bits and their placement.

This diagram from Wikipedia summarizes the expectations of the format sequence.
https://en.wikipedia.org/wiki/File:QR_Format_Information.svg

---

I used this snippet to create the `QRCode` for the following tests:

```rust
    let qrcode = QRBuilder::new("Test")
        .ecl(ECL::M)
        .version(Version::V01)
        .build()
        .unwrap();
```

With an `ECL::M`, we expect to see the ECL sequence of `[1,0]`.

In the following images, the red and blue borders highlight the format sequences, with the green highlighting the ECL sequence.

When printing to our terminal, we see the format sequences aligned correctly:

![printed_to_terminal](https://github.com/erwanvivien/fast_qr/assets/25519273/5d017ecc-fedc-4b46-a4b6-93382c271285)

However, when rendering an SVG or PNG, we notice the diagonal inversion, causing inversion of the format sequences:

![rendered_as_image](https://github.com/erwanvivien/fast_qr/assets/25519273/280f1713-d1a4-41bb-a451-3e4550c8d520)

Note that the rest of the QR code is also diagonally inverted.

**Comment by erwanvivien** [comment]
Hey, big sorry haven't seen the issue !
Checking the PR
