### ISSUE TITLE
Add customization of error code level (ecl)

### ISSUE THREAD

**Issue by matbech** [erwanvivien/fast_qr#52]
At the moment fast_qr (javascript/wasm interface) always uses the default error code level (ecl) of Q (25%). It would be desirable if this can be configured through SVGOptions. 

e.g.
```
const options = new SvgOptions()
  .ecl(ECL.Q);
```

**Comment by erwanvivien** [comment]
[fast_qr-0.12.1.tgz](https://github.com/erwanvivien/fast_qr/files/14556463/fast_qr-0.12.1.tgz)


Hey, could you try this dist and tell me if it fits your needs?

**Comment by matbech** [comment]
It is working exactly as I was looking for. Thank you.
