### ISSUE TITLE
No "main" entry in package.json

### ISSUE THREAD

**Issue by shalugin** [erwanvivien/fast_qr#59]
Hi. Why is there no `main` entry in the `package.json` file? Some tools consider it as an error:

```
Error: Failed to resolve entry for package "fast_qr". The package may have incorrect main/module/exports specified in its package.json.
```

https://www.npmjs.com/package/fast_qr?activeTab=code
```json
{
  "name": "fast_qr",
  "collaborators": [
    "erwan.vivien <erwan.vivien@epita.fr>"
  ],
  "description": "Generates optimized QRCode",
  "version": "0.12.1",
  "license": "SEE LICENSE IN LICENSE",
  "repository": {
    "type": "git",
    "url": "https://github.com/erwanvivien/fast_qr/"
  },
  "files": [
    "fast_qr_bg.wasm",
    "fast_qr.js",
    "fast_qr.d.ts"
  ],
  "module": "fast_qr.js",
  "homepage": "https://fast-qr.com/",
  "types": "fast_qr.d.ts",
  "sideEffects": false,
  "keywords": [
    "qr",
    "qrcode",
    "qr-generator",
    "qrcode-generator",
    "qr-gen"
  ]
}
```

**Comment by erwanvivien** [comment]
Hey thanks for the report!

I'm not sure why there isn't 🤔 wasm-bindgen is the one creating this file, maybe I should add a main entry by hand then!
Just to be sure, the main entry would be "fast_qr.js"?

**Comment by erwanvivien** [comment]
By the way, which tool are you using? I didn't have a problem with NPM 🤔

**Comment by shalugin** [comment]
This error message was issued by vitest (https://vitest.dev /).
I fixed it as follows (`vite.config.ts'):

```
      {
        find: /^fast_qr$/,
        replacement: __dirname + '/node_modules/fast_qr/fast_qr.js',
      },
```

**Comment by shalugin** [comment]
> Hey thanks for the report!
> 
> I'm not sure why there isn't 🤔 wasm-bindgen is the one creating this file, maybe I should add a main entry by hand then! Just to be sure, the main entry would be "fast_qr.js"?

Yes)

**Comment by erwanvivien** [comment]
It should be fixed in https://www.npmjs.com/package/fast_qr/v/0.12.5?activeTab=code

**Comment by shalugin** [comment]
Thanks for the quick fix!
