### ISSUE TITLE
Bug: Duplicate Rectangles in SVG Output

### ISSUE THREAD

**Issue by TheAwiteb** [erwanvivien/fast_qr#61]
Hi, thank you for this amazing library. I'm facing a bug where two rectangles are appearing in the resulting SVG instead of just one. The first rectangle takes the QR code background color, while the second one takes the image background color. I believe the first rectangle at [this line](https://github.com/erwanvivien/fast_qr/blob/5a1eecbae8833bb0f01ebdae08821165cac5f598/src/convert/svg.rs#L217) should be removed.

My code is
```rust
use fast_qr::{
    convert::{svg::SvgBuilder, Builder, Color},
    QRBuilder, Version, ECL,
};

const RUSTACEAN_LOGO: &str = "data:image/svg+xml;base64,BASE_64_IMAGE";

fn main() {
    let qrcode = QRBuilder::new("https://rust-lang.org")
        .ecl(ECL::Q)
        .version(Version::V03)
        .build()
        .unwrap();

    let _svg = SvgBuilder::default()
        .image(RUSTACEAN_LOGO.to_string())
        .image_background_color(Color::from([0, 0, 0, 0])) // <-- The image background is transparent
        .to_file(&qrcode, "svg.svg");
}
```

| Code Result | Should be |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/3889935a-ddee-4b6f-9809-828b8f6aa150" height="250" width="250" /> | <img src="https://github.com/user-attachments/assets/8e92f963-5fd3-4139-956f-8595c2a7e47f" height="250" width="250" /> |

**Comment by TheAwiteb** [comment]
I can open PR remove this rectangle, if i'am correct

**Comment by erwanvivien** [comment]
Thanks for the kind words and the detailed issue as well as the PR 💜
