### ISSUE TITLE
crates.io licence is "non-standard"

### ISSUE THREAD

**Issue by ejiektpobehuk** [erwanvivien/fast_qr#65]
For some reason crates.io struggles to identify a licence.

Right now `Cargo.toml` sets a licence by providing a path to the licence file. Possible workaround might be setting it explicitly with

```toml
license = "MIT"
```

ps. thanks for the project 🙏🏼

**Comment by erwanvivien** [comment]
Hey @ejiektpobehuk 👋 

Would #66 fix things for you?

**Comment by erwanvivien** [comment]
Thanks @ejiektpobehuk for the report, v0.12.6 is live: https://crates.io/crates/fast_qr/0.12.6
