### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by Adam-Alj** [erwanvivien/fast_qr#71]
[This commit](https://github.com/erwanvivien/fast_qr/commit/f4aafcb5ece85e8001ab6fe483f46e53473ee58a) recently went in, however we don't have a published version with that change just yet. 

Assuming that it is a manual process, could you please release a new version of the library? Thanks!

**Comment by erwanvivien** [comment]
Sorry about that! It's indeed manual :)

Just did it https://crates.io/crates/fast_qr/0.12.7
