### ISSUE TITLE
Prints top margin

### ISSUE THREAD

**Issue by Borber** [erwanvivien/fast_qr#8]
https://github.com/erwanvivien/fast_qr/blob/11fc725092363a54f4569af1defeb2477cbf8b09/src/helpers.rs#L31-L37

Is this paragraph for beauty? Because I think the following code should be faster

```rust
// Prints top margin without background
    println!("{}", BOTTOM.to_string().repeat(qr.size + 2));
```

**Comment by erwanvivien** [comment]
Hello, this paragraph is not for beauty,
It prints the top linz of the QRCode, the provided code would probably be faster, but this function is not used in the benchmarks

It does not matter that much, but I agree, it would be faster probably

**Comment by Borber** [comment]
> Hello, this paragraph is not for beauty, It prints the top linz of the QRCode, the provided code would probably be faster, but this function is not used in the benchmarks
> 
> It does not matter that much, but I agree, it would be faster probably

understand
